# Select the base image
FROM python:3.9-slim

# Set the work directory in the container
WORKDIR /stream_folder


# IMPORTANT NOTE:
    # The build context is the directory that Docker uses as the root for all COPY instructions. It is set by context: in docker-compose.yml (or the final argument of docker build .)
    # Every COPY path inside the Dockerfile is relative to that context directory – not to the Dockerfile’s own location.
    # It's Important to set the build context to the highest directory (root) that contains all the files you need (e.g., the project root).
    # You cannot copy files that are outside the context. 
    # A COPY path starting with '..' in the dockerfile tries to go above the context root, which Docker explicitly forbids. The build will fail with an error like “Forbidden path outside the build context”.


# Copy the entire ingestion directory that contains the producer.py and config.py scripts. These are the files we are interested in to build this container service
# Create similar directory with same contents in the container
COPY ingestion/ ./ingestion/


# Install necessary libraries needed for the producer.py script to run effectively
# Confluent-kafka is a Python client library that will establish communication between our python script and Kafka broker
# requests will enable sending requests/talk to the internet
# boto3 is a python library that enables python communicate with AWS services
RUN pip install --no-cache-dir confluent-kafka requests boto3

# Run the producer.py script
CMD [ "python", "ingestion/streaming/producer.py" ]